name: Update Zoom Links

on:
  push:
    paths:
      - 'zoom_invite.txt'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Zoom Invite Link
        id: get_zoom_link
        run: |
          ZOOM_LINK=$(cat zoom_invite.txt | tr -d '\n')
          MEETING_ID=$(echo "$ZOOM_LINK" | grep -oE 'j/[0-9]+' | cut -d'/' -f2)
          PASSWORD=$(echo "$ZOOM_LINK" | grep -oE 'pwd=[^&]+' | cut -d'=' -f2)
          echo "ZOOM_LINK=$ZOOM_LINK" >> $GITHUB_ENV
          echo "MEETING_ID=$MEETING_ID" >> $GITHUB_ENV
          echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Ensure index.html Exists
        run: |
          if [ ! -s index.html ]; then
              cat > index.html <<EOL
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Word of Hope Church - Online Service</title>
</head>
<body>
    <h1>Word of Hope Church</h1>
    <p>Join our worship service online:</p>
    <a id="zoom-web" href="[weblink]" class="btn btn-zoom">Join on Zoom (Without App - Easy Method)</a>
    <a id="zoom-app" href="[applink]" class="btn btn-zoom">Join on Zoom (With App)</a>
</body>
</html>
EOL
          fi

      - name: Update index.html with Correct Zoom Links
        run: |
          WEB_LINK="${{ env.ZOOM_LINK }}&browser=1"
          APP_LINK="zoommtg://zoom.us/join?action=join&confno=${{ env.MEETING_ID }}&pwd=${{ env.PASSWORD }}"
          
          # Ensure safe replacements
          sed -i 's|\[weblink\]|'"$WEB_LINK"'|g' index.html
          sed -i 's|\[applink\]|'"$APP_LINK"'|g' index.html

      - name: Update Zoom Deep Link File
        run: |
          echo "$APP_LINK" > zoom_deep_link.txt

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add zoom_deep_link.txt index.html
          git commit -m "Updated Zoom links" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/wordofhope/Bible_Study.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
