name: Expand Zoom Link & Update Files

on:
  issues:
    types: [opened]

jobs:
  update-zoom-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Zoom Short Link
        id: extract_zoom_link
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          SHORT_URL=$(echo "$ISSUE_BODY" | grep -oE 'https://ift\.tt/[A-Za-z0-9]+')

          if [[ -z "$SHORT_URL" ]]; then
            echo "No short URL found. Exiting."
            exit 1
          fi

          echo "SHORT_URL=$SHORT_URL" >> $GITHUB_ENV

      - name: Expand Short URL
        id: expand_url
        run: |
          LONG_URL=$(curl -Ls -o /dev/null -w %{url_effective} "${SHORT_URL}")

          if [[ -z "$LONG_URL" ]]; then
            echo "Failed to expand URL. Exiting."
            exit 1
          fi

          echo "LONG_URL=$LONG_URL" >> $GITHUB_ENV

      - name: Extract Meeting ID & Password
        id: extract_details
        run: |
          MEETING_ID=$(echo "$LONG_URL" | grep -oE 'j/[0-9]+' | cut -d'/' -f2)
          PASSWORD=$(echo "$LONG_URL" | grep -oE 'pwd=[^&]+' | cut -d'=' -f2)

          echo "MEETING_ID=$MEETING_ID" >> $GITHUB_ENV
          echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Update index.html (With Styling)
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang=\"en\">" >> index.html
          echo "<head>" >> index.html
          echo "    <meta charset=\"UTF-8\">" >> index.html
          echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> index.html
          echo "    <title>Word of Hope Church - Online Service</title>" >> index.html
          echo "    <style>" >> index.html
          echo "        body { font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f4f4; color: #333; text-align: center; }" >> index.html
          echo "        header { background-color: #6200EA; color: white; padding: 20px 10px; }" >> index.html
          echo "        header h1 { margin: 0; }" >> index.html
          echo "        .container { max-width: 800px; margin: 50px auto; padding: 20px; background: white; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); border-radius: 10px; }" >> index.html
          echo "        .btn { display: inline-block; margin: 15px 0; padding: 15px 25px; font-size: 18px; color: white; text-decoration: none; border-radius: 5px; transition: background-color 0.3s; }" >> index.html
          echo "        .btn-youtube { background-color: #FF0000; }" >> index.html
          echo "        .btn-youtube:hover { background-color: #CC0000; }" >> index.html
          echo "        .btn-zoom { background-color: #0078D7; }" >> index.html
          echo "        .btn-zoom:hover { background-color: #005FA4; }" >> index.html
          echo "        footer { margin-top: 50px; padding: 20px; background-color: #333; color: white; }" >> index.html
          echo "    </style>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "    <header>" >> index.html
          echo "        <h1>Word of Hope Church</h1>" >> index.html
          echo "        <p>Pastor Jerry Seigle</p>" >> index.html
          echo "    </header>" >> index.html
          echo "    <div class=\"container\">" >> index.html
          echo "        <h2>Join Our Worship Service Online</h2>" >> index.html
          echo "        <p>We are so glad to have you worship with us!</p>" >> index.html
          echo "        <a href=\"https://www.youtube.com/channel/UCQQk_ZMqz1uuFVXawbVbvtw/\" class=\"btn btn-youtube\">Watch on YouTube</a>" >> index.html
          echo "        <br>" >> index.html
          echo "        <a href=\"https://zoom.us/wc/join/${MEETING_ID}?pwd=${PASSWORD}\" class=\"btn btn-zoom\">Join on Zoom (Web Client)</a>" >> index.html
          echo "        <br>" >> index.html
          echo "        <a href=\"${LONG_URL}\" class=\"btn btn-zoom\">Join on Zoom (With App)</a>" >> index.html
          echo "    </div>" >> index.html
          echo "    <footer>" >> index.html
          echo "        <p>&copy; 2025 Word of Hope Church. All Rights Reserved.</p>" >> index.html
          echo "    </footer>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      - name: Update Zoom Deep Link File
        run: |
          echo "zoommtg://zoom.us/join?action=join&confno=${MEETING_ID}&pwd=${PASSWORD}" > zoom_deep_link.txt

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html zoom_deep_link.txt
          git commit -m "Updated Zoom links from GitHub issue with styling" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/wordofhope/Bible_Study.git HEAD:main
